# This file contains confinguration options for the MPF itself, including
# default settings for your pinball machines.

# You should create specific subfolders for each game you want to make and put
# config files there to override these defaults.


# Configuration for the MPF framework itself

MPF:
    system_modules:  # order is important here
        timing.Timing
        events.EventManager
        switch_controller.SwitchController
        ball_controller.BallController
        show_controller.ShowController
    device_modules:
        driver.Driver
        switch.Switch
        matrix_light.MatrixLight
        led.LED
        gi.GI
        autofire.AutofireCoil
        ball_device.BallDevice
        drop_target.DropTarget
        drop_target.DropTargetBank
        target.Target
        target.TargetGroup
        rollover.Rollover
        rollover.RolloverGroup
        flipper.Flipper
        diverter.Diverter
        score_reel.ScoreReel
        score_reel.ScoreReelGroup
    paths:
        scriptlets: scriptlets
        shows: shows
        audits: audits/audits.yaml
    auto_load_shows: True
    default_pulse_ms: 10
    default_debounce_ms: 0  # fast only

# Default settings for machines. All can be overridden

Machine:
    HZ: 30
    Balls Installed: 1
    Min Balls: 1
    Max Balls: 10

Hardware:
    Platform: virtual

Game:
    Balls per game: 3
    Max players per game: 2

MachineFlow:
    mpf.game.attract.Attract
    mpf.game.game.Game

OSC:
    machine_ip: auto
    machine_port: 8000
    approved_client_ips: any
    client_port: 9000
    debug_messages: false
    client_updates:
        switches
        lights
        data

Auditor:
    save_events:
        game_started
        ball_ended
        game_ended
    num_player_top_records: 10
    audit:
        shots
        switches
        events
        player
    events:
        ball_search_begin_phase1
        game_started
        game_ended
    player:
        score

BallSearch:
    Secs until ball search start: 10
    Secs between ball search rounds: 3
    Secs between ball search coils: .15
    If ball search fails: Keep Looking

Language:
    en

LCD:
    width: 800
    height: 600
    title: Mission Pinball Framework
    items:
        score
        player
        ball
        version
        title
        looprate

LogicBlocks:

    HitCounters:

        tilt:
            trigger_events: sw_tilt
            event_when_hit: tilt_hit
            hits_to_complete: 3
            events_when_complete: tilt
            multiple_hit_window: 500ms
            enable_events: ball_started
            disable_events: game_ended
            reset_events: ball_ended
            events_when_complete: tilt
            restart_on_complete: false
            settle_time: 5s

        slam_tilt:
            trigger_events: sw_slamTilt
            enable_events: game_started
            hits_to_complete: 1
            events_when_complete: slam_tilt