# Instructions for this config file:
# https://missionpinball.com/docs/configuration-file-reference/

# bonus
# bonus section
# is scoring and shots separate?
# prob yes
# types
# sequence - must hit them in order within time specified
# any (default) - must hit any one


Shots:
    RightRamp:
        Switch: rightRampExit
    LeftRamp:
        Type: Sequence
        Switches: leftRampEnter, leftRampExit
        Time: 3s
    LeftOrbit:
        Type: Sequence
        Switches: leftRollover, topRightOpto
        Time: 3s
    WeakRightOrbit:
        Type: Sequence
        Switches: topRightOpto, topCenterRollover
        Time: 3s
    FullRightOrbit:
        Type: Sequence
        Switches: topRightOpto, leftRollover
        Time: 3s
    AirRaidRamp:
        Switch: topRampExit
    OrangeStandups:
        Switch: threeBankTargets
    Slingshot:
        Switch: slingR, slingL
    Inlane:
        Switch: inlaneL, inlaneR, outerInlaneR
    Outlane:
        Switch: outlaneR, outlaneL
    DropTarget:
        Switch: dropTargetJ, dropTargetU, dropTargetD, dropTargetG, dropTargetE

Scoring:
    shot_RightRamp:
        Score: 8000
    shot_LeftRamp:
        Score: 7000
    shot_LeftOrbit:
        Score: 6000
    shot_WeakRightOrbit:
        Score: 11000
    shot_FullRightOrbit:
        Score:  6500
    shot_AirRaidRamp:
        Score: 10000
    shot_OrangeStandups:
        Score: 2500
    shot_Slingshot:
        Score: 210
    shot_Inlane:
        Score: 1070
    shot_Outlane:
        Score: 930
    shot_DropTarget:
        Score: 1000
    drop_targets_Judge_complete:
        Score: 10000
    standups_pf_standups_complete:
        Score: 5000